# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = imageEnhanceByOpenCV
DESTDIR = ./debug
CONFIG += debug
DEFINES += _WINDOWS _UNICODE QT_DEPRECATED_WARNINGS
LIBS += -lshell32
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += ./GeneratedFiles
include(imageEnhanceByOpenCV.pri)
